import os
import argparse

def _peptide_total_charge(smi_file_path: str) -> int:
    """Calculate the total charge of a peptide from its SMILES representation.

    Args:
        smi_file_path (str): Path to the SMILES file.

    Returns:
        int: Total charge (int).
    """
    with open(smi_file_path, 'r') as f:
        smiles = f.readline().strip()
    positive_charges = smiles.count('+')
    negative_charges = smiles.count('-')
    return positive_charges - negative_charges

def _pdb_to_xyz(pdb_path: str, xyz_path: str) -> None:
    """Convert a PEP-EDIT PDB file to XYZ format.

    Args:
        pdb_path (str): path to the PDB file.
        xyz_path (str): path to write the XYZ file.
    """
    atoms = []
    with open(pdb_path, "r") as f:
        for line in f:
            if line.startswith(("ATOM", "HETATM")):
                element = line[76:78].strip()
                
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                atoms.append((element, x, y, z))
    with open(xyz_path, "w") as out:
        out.write(f"{len(atoms)}\n")
        out.write(f"Converted from {os.path.basename(pdb_path)}\n")
        for element, x, y, z in atoms:
            out.write(f"{element:<3}  {x:15.8f}  {y:15.8f}  {z:15.8f}\n")

def prepare_orca_inp_file(pep_edit_pdb_path, pep_edit_smi_path, output_dir, method='XTB', alpb_water=True, nprocs=8, maxcore=23000):
    """Prepare ORCA input files from PEP-EDIT outputs. It generates a XYZ file and an ORCA input file.

    Args:
        pep_edit_pdb_path (str): Path to the PEP-EDIT generated PDB file.
        pep_edit_smi_path (str): Path to the PEP-EDIT generated SMILES file.
        output_dir (str): Directory to save the ORCA input file and XYZ file.
        method (str, optional): The method to use for the calculation. Defaults to 'XTB'.
        alpb_water (bool, optional): Whether to use the ALPB model for water. Defaults to True.
        nprocs (int, optional): The number of processors to use. Defaults to 8.
        maxcore (int, optional): The maximum amount of memory to use (in MB). Defaults to 23000.
    """
    basename = os.path.basename(pep_edit_pdb_path).replace(".pdb", "")
    os.makedirs(output_dir, exist_ok=True)
    _pdb_to_xyz(pep_edit_pdb_path, os.path.join(output_dir, f"{basename}.xyz"))
    charge = _peptide_total_charge(pep_edit_smi_path)
    solv_arg = "ALPB(water)" if alpb_water else ""
    line1 = f"!GOAT {method} {solv_arg}"
    line2 = f"%PAL NPROCS {nprocs} END"
    line3 = f"%maxcore {maxcore}"
    line4 = f"*XYZFILE {charge} 1 {basename}.xyz"
    inp_content = "\n\n".join([line1, line2, line3, line4])
    inp_path = os.path.join(output_dir, f"{basename}.inp")
    with open(inp_path, 'w') as f:
        f.write(inp_content)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Prepare ORCA input files from PEP-EDIT outputs. You only need to provide the PDB and SMILES files generated by PEP-EDIT.")
    parser.add_argument("pep_edit_pdb_path", type=str, help="Path to the PEP-EDIT generated PDB file.")
    parser.add_argument("pep_edit_smi_path", type=str, help="Path to the PEP-EDIT generated SMILES file.")
    parser.add_argument("output_dir", type=str, help="Directory to save the ORCA input file and XYZ file.")
    parser.add_argument("--method", type=str, default="XTB", help="The method to use for the calculation.")
    parser.add_argument("--alpb_water", action="store_true", help="Whether to use the ALPB model for water.")
    parser.add_argument("--nprocs", type=int, default=8, help="The number of processors to use.")
    parser.add_argument("--maxcore", type=int, default=23000, help="The maximum amount of memory to use (in MB).")

    args = parser.parse_args()

    prepare_orca_inp_file(args.pep_edit_pdb_path, args.pep_edit_smi_path, args.output_dir, args.method, args.alpb_water, args.nprocs, args.maxcore)